version: "3"
services:
    nginx:
        image: "nginx:latest"
        restart: "always"
        volumes:
        #   - ./nginx-web/dist:/usr/share/nginx/html
        - ./configs/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "8000:80"
    booksalon-gin:
        build: .
        restart: "always"
        expose:
        - "8000"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        # 环境变量
        environment:
            # mysql密码
            - MYSQL_ROOT_PASSWORD={123456}
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.1
        container_name: "booksalon-mysql"


networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16